spring:
  profiles:
    group:
      "local": "onLocalToDb"
      "dev": "onServerToDb"
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: "jdbc:log4jdbc:postgresql://192.168.56.1:5432/mydb"
    username: postgres
    password: "!Aa202020"

    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 20

  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"

logging:
  config: classpath:logback.xml

mybatis:
  mapper-locations: "classpath:mybatis/mapper/**/**.xml"
server:
  ssl:
    key-store: "classpath:mingi-keystore.p12"
    key-store-type: PKCS12
    key-alias: mingi-keystore
    key-store-password: 202020

---
spring:
  config:
    activate:
      on-profile: onLocalToDb
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://192.168.56.1:5432/mydb"
    username: postgres
    password: "!Aa202020"

---
spring:
  config:
    activate:
      on-profile: onServerToDb
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/mydb"
    username: postgres
    password: "!Aa202020"
